# Generated by Django 4.2.11 on 2025-05-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floto_api', '0024_alter_application_deleted_alter_collection_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('START', 'Start'), ('STOP', 'Stop')], default='START', max_length=32),
            preserve_default=False,
        ),
    ]
